apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "devops-task-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: my-node-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - "ALL"
            seccompProfile:
              type: RuntimeDefault
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
