apiVersion: v1
kind: Service
metadata:
  name: {{ template "devops-task-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: my-node-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
